const form=document.getElementById('f');const fields=[...form.querySelectorAll('input,textarea,select')];const fill=document.getElementById('fill');const pct=document.getElementById('pct');const out=document.getElementById('out');const summary=document.getElementById('summary');const toast=document.getElementById('toast');const KEY='andressa_anamnese_v3';
const musculos=['Glúteos','Posterior de coxa','Quadríceps','Panturrilhas','Abdômen/core','Costas','Ombros','Braços','Peitoral','Corpo inteiro'];document.querySelectorAll('[name^="p"]').forEach(s=>musculos.forEach(m=>s.add(new Option(m,m))));
function val(name){const el=form.elements[name];if(!el)return'';if(el instanceof RadioNodeList)return el.value||'';return (el.value||'').trim()}
function checked(name){return [...form.querySelectorAll(`input[name="${name}"]:checked`)].map(i=>i.value)}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
function toggle(){document.getElementById('dor-extra').classList.toggle('show',val('dor')==='Sim');document.getElementById('med-extra').classList.toggle('show',val('medica')==='Sim')}
function progress(){const secs=[...document.querySelectorAll('[data-s]')];let done=0;secs.forEach(sec=>{const cs=[...sec.querySelectorAll('input,textarea,select')];if(cs.some(c=>c.type==='radio'||c.type==='checkbox'?c.checked:(c.value||'').trim()))done++});const n=Math.round(done/secs.length*100);fill.style.width=n+'%';pct.textContent=n+'%'}
function save(){const data={};fields.forEach(f=>{if(f.type==='radio'){if(f.checked)data[f.name]=f.value}else if(f.type==='checkbox'){data[f.name]=(data[f.name]||[]);if(f.checked)data[f.name].push(f.value)}else data[f.name]=f.value});localStorage.setItem(KEY,JSON.stringify(data));toggle();progress()}
function load(){const raw=localStorage.getItem(KEY);if(!raw){toggle();progress();return}const data=JSON.parse(raw);fields.forEach(f=>{if(f.type==='radio')f.checked=data[f.name]===f.value;else if(f.type==='checkbox')f.checked=(data[f.name]||[]).includes(f.value);else if(data[f.name]!==undefined)f.value=data[f.name]});toggle();progress()}
fields.forEach(f=>{f.addEventListener('change',save);f.addEventListener('input',save)});load();
function text(){const r=checked('regioes').join(', ');const d=checked('dias').join(', ');return `ANAMNESE DE TREINO — ANDRESSA\n\n1. OBJETIVO\nObjetivo: ${val('objetivo')||'-'}\nMudança desejada: ${val('mudanca')||'-'}\n\n2. PRIORIDADES\nRegiões: ${r||'-'}\n1ª prioridade: ${val('p1')||'-'}\n2ª prioridade: ${val('p2')||'-'}\n3ª prioridade: ${val('p3')||'-'}\nPonto forte: ${val('forte')||'-'}\nDesenvolver mais: ${val('fraco')||'-'}\n\n3. EXPERIÊNCIA\nTreina atualmente: ${val('treina')||'-'}\nTempo de treino: ${val('tempo')||'-'}\nNível: ${val('nivel')||'-'}\n\n4. ROTINA\nFrequência: ${val('freq')||'-'}\nTempo por treino: ${val('tempoTreino')||'-'}\nMelhores dias: ${d||'-'}\nDescanso preferido: ${val('descanso')||'-'}\n\n5. PREFERÊNCIAS\nGosta: ${val('gosta')||'-'}\nEvita/não gosta: ${val('naogosta')||'-'}\nEstilo: ${val('estilo')||'-'}\nPróximo do limite: ${val('limite')||'-'}\nEquipamentos: ${val('equip')||'-'}\n\n6. ESTRUTURA\nLocal: ${val('local')||'-'}\nIndisponíveis: ${val('indisponivel')||'-'}\n\n7. CONFORTO E LIMITAÇÕES\nDor/limitação: ${val('dor')||'-'}\nDetalhes: ${val('dorDetalhe')||'-'}\nExercícios evitados: ${val('evita')||'-'}\nRecomendação médica/profissional: ${val('medica')||'-'}\nDetalhes da recomendação: ${val('medicaDetalhe')||'-'}\n\n8. TREINO IDEAL\nO que faria o treino parecer feito para você: ${val('feito')||'-'}\nO que não pode faltar: ${val('naofalta')||'-'}\nResultado desejado: ${val('frase')||'-'}\n`}
document.getElementById('finish').onclick=()=>{summary.textContent=text();out.showModal()};document.getElementById('close').onclick=()=>out.close();document.getElementById('copyBtn').onclick=async()=>{await navigator.clipboard.writeText(summary.textContent);showToast('Resumo copiado!')};document.getElementById('downloadBtn').onclick=()=>{const blob=new Blob([summary.textContent],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='anamnese-andressa.txt';a.click();URL.revokeObjectURL(a.href)};document.getElementById('shareBtn').onclick=async()=>{try{if(navigator.share)await navigator.share({title:'Anamnese de Treino — Andressa',text:summary.textContent});else{await navigator.clipboard.writeText(summary.textContent);showToast('Resumo copiado!')}}catch(e){}};document.getElementById('clear').onclick=()=>{if(!confirm('Deseja limpar todas as respostas?'))return;localStorage.removeItem(KEY);form.reset();toggle();progress();showToast('Respostas limpas.')};
